### ISSUE TITLE
Editing Notes

### ISSUE THREAD

**Issue by Pavan-Sai-padavala** [CareerDevelopmentHub/magic-notes#11]
there is no edit feature, which restricts our points that can be added later
![image](https://github.com/CareerDevelopmentHub/magic-notes/assets/72682254/cd1b2abc-895e-4031-ba2c-d884fd5e4d7a)

**Comment by Pavan-Sai-padavala** [comment]
assign this to me

**Comment by MrDBC** [comment]
im working on it

**Comment by Pavan-Sai-padavala** [comment]
Please continue

**Comment by MrDBC** [comment]
@anuragkmr45 can u review my PR once?
#19

**Comment by anuragkmr45** [comment]
@MrDBC  working great

**Comment by MrDBC** [comment]
thanks @anuragkmr45  😊
