### ISSUE TITLE
Sort notes

### ISSUE THREAD

**Issue by anuragkmr45** [CareerDevelopmentHub/magic-notes#13]
Sort list of notes on the bases of -
1. Date assenting and descending
2. Imp tags
3. No of words

**Comment by apikmeister** [comment]
I have done this, will open pull request after the star feature has been merged.

**Comment by anuragkmr45** [comment]
@apikmeister did not found your PR

**Comment by apikmeister** [comment]
#21 Just make a pr that comply with my important-tags pull request.

**Comment by anuragkmr45** [comment]
@apikmeister well dome
