### ISSUE TITLE
Add date section to the notes

### ISSUE THREAD

**Issue by anuragkmr45** [CareerDevelopmentHub/magic-notes#14]

**Comment by Levyathanus** [comment]
Hi, I would like to work on this issue. Should every note report a timestamp or just the date?

**Comment by anuragkmr45** [comment]
@Levyathanus  sure giving timestamp is much better option

**Comment by Levyathanus** [comment]
Great, I've opened a PR for this!

**Comment by anuragkmr45** [comment]
well done
