### ISSUE TITLE
Note Header

### ISSUE THREAD

**Issue by kom-senapati** [CareerDevelopmentHub/magic-notes#30]
![image](https://github.com/CareerDevelopmentHub/magic-notes/assets/92045934/f567aab7-5fea-40a3-8938-0a591a6fdc18)

A note header/title can be implemented here.
I would like to work on this issue.

**Comment by kom-senapati** [comment]
Instead of Note# it will show that title

**Comment by anuragkmr45** [comment]
@kom-senapati also try to make image smaller
