### ISSUE TITLE
Search In list of notes

### ISSUE THREAD

**Issue by anuragkmr45** [CareerDevelopmentHub/magic-notes#8]
Make a search bar from which any one can search particular notes

**Comment by anuragkmr45** [comment]
no need for whole note just by typing some word

**Comment by dalalsoham** [comment]
please assign me this task plz

**Comment by anuragkmr45** [comment]
@dalalsoham  assigned

**Comment by Pratik-k-sahoo** [comment]
@anuragkmr45 I have added the search bar where user can search particular note. Please review it and accept the pull request.
